module.exports = [
  {
    title: "Engagement Ceremony Decor",
    category: "ceremony",
    type: "onsite",
    price: 18000,
    durationMins: 150,
    description: "Elegant stage decor with floral panels, lighting & seating",
    image:
      "https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=1200&q=60",
    tags: ["Engagement", "Stage", "Lighting"],
    active: true,
  },
  {
    title: "Mehendi Night Decoration",
    category: "ceremony",
    type: "onsite",
    price: 12000,
    durationMins: 120,
    description: "Colorful drapes, marigold flowers & ethnic props",
    image:
      "https://images.unsplash.com/photo-1609357603884-34baf6f5edb6?auto=format&fit=crop&w=1200&q=60",
    tags: ["Mehendi", "Ethnic", "Flowers"],
    active: true,
  },
  {
    title: "Haldi Ceremony Decor",
    category: "ceremony",
    type: "onsite",
    price: 10000,
    durationMins: 120,
    description: "Yellow-themed floral decor with seating & backdrop",
    image:
      "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=60",
    tags: ["Haldi", "Floral", "Backdrop"],
    active: true,
  },
  {
    title: "Reception Entrance Decor",
    category: "ceremony",
    type: "onsite",
    price: 14000,
    durationMins: 120,
    description: "Floral gate, lights & carpet walkway",
    image:
      "https://images.unsplash.com/photo-1582719478148-d7b6b6b11b69?auto=format&fit=crop&w=1200&q=60",
    tags: ["Reception", "Entrance", "Floral"],
    active: true,
  },
  {
    title: "Nikah Ceremony Minimal Decor",
    category: "ceremony",
    type: "onsite",
    price: 9000,
    durationMins: 90,
    description: "Simple stage backdrop + lights + floral touch",
    image:
      "https://images.unsplash.com/photo-1523438097201-512ae7d59cfc?auto=format&fit=crop&w=1200&q=60",
    tags: ["Nikah", "Minimal", "Backdrop"],
    active: true,
  },
  {
    title: "Gaye Holud Floral Setup",
    category: "ceremony",
    type: "onsite",
    price: 16000,
    durationMins: 150,
    description: "Floral wall + seating + lighting for Holud",
    image:
      "https://images.unsplash.com/photo-1529636798458-92182e662485?auto=format&fit=crop&w=1200&q=60",
    tags: ["Holud", "FloralWall", "Lighting"],
    active: true,
  },
  {
    title: "Anniversary Celebration Decor",
    category: "home",
    type: "onsite",
    price: 8000,
    durationMins: 90,
    description: "Romantic balloon, candle & light decoration",
    image:
      "https://images.unsplash.com/photo-1504805572947-34fad45aed93?auto=format&fit=crop&w=1200&q=60",
    tags: ["Anniversary", "Romantic", "Lights"],
    active: true,
  },
  {
    title: "Baby Shower Decoration",
    category: "home",
    type: "onsite",
    price: 7000,
    durationMins: 90,
    description: "Pastel balloon decor with themed props & backdrop",
    image:
      "https://images.unsplash.com/photo-1558021212-51b6ecfa0db9?auto=format&fit=crop&w=1200&q=60",
    tags: ["BabyShower", "Balloon", "Theme"],
    active: true,
  },
  {
    title: "Room Surprise Decoration",
    category: "home",
    type: "onsite",
    price: 5000,
    durationMins: 60,
    description: "Bed balloons, candles, rose petals & lights",
    image:
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=60",
    tags: ["Surprise", "Romantic", "RoomDecor"],
    active: true,
  },
  {
    title: "Kids Theme Party Decor",
    category: "home",
    type: "onsite",
    price: 9000,
    durationMins: 90,
    description: "Cartoon theme backdrop, balloons & props",
    image:
      "https://images.unsplash.com/photo-1605902711622-cfb43c4437d1?auto=format&fit=crop&w=1200&q=60",
    tags: ["Kids", "ThemeParty", "Backdrop"],
    active: true,
  },
  {
    title: "Custom Theme Planning Session",
    category: "ceremony",
    type: "studio",
    price: 2500,
    durationMins: 60,
    description: "One-on-one theme & budget planning with mood board",
    image:
      "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=60",
    tags: ["Custom", "Planning", "Theme"],
    active: true,
  },
  {
    title: "Budget Decoration Consultation",
    category: "home",
    type: "studio",
    price: 1000,
    durationMins: 30,
    description: "Quick consultation for small home events",
    image:
      "https://images.unsplash.com/photo-1556761175-129418cb2dfe?auto=format&fit=crop&w=1200&q=60",
    tags: ["Budget", "Consultation"],
    active: true,
  },
];

// module.exports = [
//   {
//     title: "Wedding Stage Premium",
//     category: "ceremony",
//     type: "onsite",
//     price: 25000,
//     durationMins: 180,
//     description: "Stage + floral + lighting + full setup",
//     image:
//       "https://images.unsplash.com/photo-1523438097201-512ae7d59cfc?auto=format&fit=crop&w=1200&q=60",
//     tags: ["Stage", "Floral", "Lighting"],
//     active: true,
//   },
//   {
//     title: "Home Birthday Decor",
//     category: "home",
//     type: "onsite",
//     price: 6000,
//     durationMins: 90,
//     description: "Balloon arch + backdrop + table setup",
//     image:
//       "https://images.unsplash.com/photo-1520857014576-2c4f4c972b57?auto=format&fit=crop&w=1200&q=60",
//     tags: ["Balloon", "Backdrop", "Props"],
//     active: true,
//   },
//   {
//     title: "Studio Consultation",
//     category: "ceremony",
//     type: "studio",
//     price: 1500,
//     durationMins: 45,
//     description: "In-studio consultation with concept & budget plan",
//     image:
//       "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=60",
//     tags: ["Consultation", "Planning"],
//     active: true,
//   },
// ];
